# 检查配置文件变动的时间间隔
refresh_rate = "30 seconds"

[appenders.stdout]
kind = "console"
encoder.pattern = "{d(%Y-%m-%d %H:%M:%S %Z)(local)} {h({l:>5.5})} {P} [{T:>18.18}] {h({M:>27.27})}: {m}{n}"

[appenders.requests]
kind = "rolling_file"
path = "log/server.log"
encoder.pattern = "{d(%Y-%m-%d %H:%M:%S %Z)(local)} {h({l:>5.5})} {P} [{T:>18.18}] {h({M:>27.27})}: {m}{n}"
policy.kind = "compound"
policy.trigger.kind = "size"
policy.trigger.limit = "20 mb"
policy.roller.kind = "fixed_window"
policy.roller.pattern = 'log/server.log.{{}}'
policy.roller.base = 1
policy.roller.count = 5

[appenders.access]
kind = "rolling_file"
path = "log/access.log"
encoder.pattern = "{d(%Y-%m-%d %H:%M:%S %Z)(local)} {h({l:>5.5})} {P} [{T:>18.18}] {h({M:>27.27})}: {m}{n}"
policy.kind = "compound"
policy.trigger.kind = "size"
policy.trigger.limit = "20 mb"
policy.roller.kind = "fixed_window"
policy.roller.pattern = 'log/access.log.{{}}'
policy.roller.base = 1
policy.roller.count = 5

[root]
level = "debug"
appenders = ["stdout", "requests"]

[loggers]
"rain_web".level = "debug"
"sqlx::query".level = "debug"
"actix_web::middleware::logger".level = "info"
"actix_web::middleware::logger".appenders = ["access"]
"actix_web::middleware::logger".additive = false